---
version: 1.0.x.{build}
clone_depth: 10
install:
  - ps: '& .\extras\install.ps1'
build: off
test_script:
  - ps: '& .\src\tests\pester.ps1'
  - ps: '& .\build.ps1 -PowerShellModuleName PowerShellGet -ErrorAction Stop -Verbose -PassThru'
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
